name: Analyze Images
on: 
    push:
    schedule:
        - cron: '25 17 * * MON'   # Every Monday at 5:25 PM UTC

permissions:
    security-events: write
    contents: read

jobs:
    discover:
        name: Generate Analysis Matrix
        runs-on: ubuntu-latest
        outputs:
            matrix: ${{steps.discover.outputs.matrix}}
        
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v6

            - name: Discover Images
              id: discover
              run: |
                echo "matrix=$(python3 .github/scripts/image_discovery.py \
                    --analysis \
                    --base-img-repo '${{vars.BASE_IMAGES_REPO}}' \
                    --svc-img-repo '${{vars.SERVICE_IMAGES_REPO}}')" >> "$GITHUB_OUTPUT"

    analyze:
        needs: discover
        name: ${{matrix.tag}}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                include: ${{fromJSON(needs.discover.outputs.matrix)}}

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v6

            - name: Run Trivy Vulnerability Scanner
              uses: aquasecurity/trivy-action@v0.36.0
              with:
                  image-ref: "docker.io/${{matrix.image}}:${{matrix.tag}}"
                  format: "template"
                  template: "@/contrib/sarif.tpl"
                  output: "trivy-results_${{matrix.tag}}.sarif"
                  scanners: "vuln,secret,config"
                  severity: "CRITICAL,HIGH"
                  limit-severities-for-sarif: true

            - name: Upload Trivy Scan Results
              uses: github/codeql-action/upload-sarif@v4
              with:
                  sarif_file: "trivy-results_${{matrix.tag}}.sarif"
