name: Analyze all BASE images
on: 
    push:
    schedule:
        - cron: '50 14 * * MON'   # Every Monday at 2:50 PM UTC

permissions:
    security-events: write
    contents: read

jobs:
    default_ubuntu_jammy:
        name: Default Ubuntu 22.04
        uses: ./.github/workflows/analyze-image.yml
        with:
            image: samyarsadat/custom_base_images
            image_tag: default-ubuntu-22.04
            analysis_name: default-ubuntu-22.04

    default_ubuntu_noble:
        name: Default Ubuntu 24.04
        uses: ./.github/workflows/analyze-image.yml
        with:
            image: samyarsadat/custom_base_images
            image_tag: default-ubuntu-24.04
            analysis_name: default-ubuntu-24.04

    default_alpine_latest:
        name: Default Alpine Latest
        uses: ./.github/workflows/analyze-image.yml
        with:
            image: samyarsadat/custom_base_images
            image_tag: default-alpine-latest
            analysis_name: default-alpine-latest

    base_ros_humble:
        name: Base ROS Humble
        uses: ./.github/workflows/analyze-image.yml
        with:
            image: samyarsadat/custom_base_images
            image_tag: base-ros-humble
            analysis_name: base-ros-humble

    base_ros_jazzy:
        name: Base ROS Jazzy
        uses: ./.github/workflows/analyze-image.yml
        with:
            image: samyarsadat/custom_base_images
            image_tag: base-ros-jazzy
            analysis_name: base-ros-jazzy

    base_ros_vulcanexus_humble:
        name: Base ROS Humble w/ Vulcanexus
        uses: ./.github/workflows/analyze-image.yml
        with:
            image: samyarsadat/custom_base_images
            image_tag: base-ros-vulcanexus-humble
            analysis_name: base-ros-vulcanexus-humble

    base_ros_vulcanexus_jazzy:
        name: Base ROS Jazzy w/ Vulcanexus
        uses: ./.github/workflows/analyze-image.yml
        with:
            image: samyarsadat/custom_base_images
            image_tag: base-ros-vulcanexus-jazzy
            analysis_name: base-ros-vulcanexus-jazzy

    full_ros_humble:
        name: Full Desktop ROS Humble
        uses: ./.github/workflows/analyze-image.yml
        with:
            image: samyarsadat/custom_base_images
            image_tag: desktop-full-ros-humble
            analysis_name: desktop-full-ros-humble

    full_ros_jazzy:
        name: Full Desktop ROS Jazzy
        uses: ./.github/workflows/analyze-image.yml
        with:
            image: samyarsadat/custom_base_images
            image_tag: desktop-full-ros-jazzy
            analysis_name: desktop-full-ros-jazzy