name: Analyze Image Using Trivy
on: 
    workflow_call:
        inputs:
            image: 
                description: "The image to analyze."
                required: true
                type: string
            image_tag:
                description: "The tag of the image to analyze."
                required: true
                type: string
            analysis_name:
                description: "The name of the analysis. This will be used in the output file name. It should be unique for each analysis."
                required: true
                type: string

jobs:
    analyze_image:
        name: Analyze ${{inputs.image}}:${{inputs.image_tag}}
        runs-on: ubuntu-latest
        permissions:
            contents: read
            security-events: write

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Run Trivy Vulnerability Scanner
              uses: aquasecurity/trivy-action@0.23.0
              with:
                  image-ref: "docker.io/${{inputs.image}}:${{inputs.image_tag}}"
                  format: "template"
                  template: "@/contrib/sarif.tpl"
                  output: "trivy-results_${{inputs.analysis_name}}.sarif"
                  scanners: "vuln,secret,config"
                  severity: "CRITICAL,HIGH"
                  limit-severities-for-sarif: true

            - name: Upload Trivy Scan Results
              uses: github/codeql-action/upload-sarif@v3
              with:
                  sarif_file: "trivy-results_${{inputs.analysis_name}}.sarif"