name: Analyze Image Using Trivy
on: 
    workflow_call:
        inputs:
            image: 
                description: "The image to analyze."
                required: true
                type: string
            image_tag:
                description: "The tag of the image to analyze."
                required: true
                type: string

jobs:
    analyze:
        name: Analyze ${{inputs.image}}:${{inputs.image_tag}}
        runs-on: "ubuntu-20.04"
        permissions:
            contents: read
            security-events: write

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Run Trivy Vulnerability Scanner
              uses: aquasecurity/trivy-action@0.23.0
              with:
                  image-ref: "docker.io/${{inputs.image}}:${{inputs.image_tag}}"
                  format: "template"
                  template: "@/contrib/sarif.tpl"
                  output: "trivy-results_${{inputs.image}}:${{inputs.image_tag}}.sarif"

            - name: Upload Trivy Scan Results
              uses: github/codeql-action/upload-sarif@v2
              with:
                  sarif_file: "trivy-results_${{inputs.image}}:${{inputs.image_tag}}.sarif"
