name: Analyze Image Using Trivy
on: 
    workflow_call:
        inputs:
            image: 
                description: "the image to analyze"
                required: true
                type: string
            image_tag:
                description: "the tag of the image to analyze"
                required: true
                type: string
            analysis_name:
                description: "the name of the analysis, should be unique for each analysis"
                required: true
                type: string

jobs:
    analyze_image:
        name: Trivy Analyze
        runs-on: ubuntu-latest
        permissions:
            contents: read
            security-events: write

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v6

            - name: Run Trivy Vulnerability Scanner
              uses: aquasecurity/trivy-action@v0.36.0
              with:
                  image-ref: "docker.io/${{inputs.image}}:${{inputs.image_tag}}"
                  format: "template"
                  template: "@/contrib/sarif.tpl"
                  output: "trivy-results_${{inputs.analysis_name}}.sarif"
                  scanners: "vuln,secret,config"
                  severity: "CRITICAL,HIGH"
                  limit-severities-for-sarif: true

            - name: Upload Trivy Scan Results
              uses: github/codeql-action/upload-sarif@v4
              with:
                  sarif_file: "trivy-results_${{inputs.analysis_name}}.sarif"