name: Analyze all SERVICE images
on: 
    push:
    schedule:
        - cron: '50 16 * * MON'   # Every Monday at 4:50 PM UTC

permissions:
    security-events: write
    contents: read

jobs:
    serverpi_caddy_latest:
        name: ServerPi Caddy Latest
        uses: ./.github/workflows/analyze-image.yml
        with:
            image: samyarsadat/service_images
            image_tag: serverpi-caddy-latest
            analysis_name: serverpi-caddy-latest

    serverpi_wgeasy_latest:
        name: ServerPi WireGuard-Easy Latest
        uses: ./.github/workflows/analyze-image.yml
        with:
            image: samyarsadat/service_images
            image_tag: serverpi-wgeasy-latest
            analysis_name: serverpi-wgeasy-latest

    pico_build_action_latest:
        name: Pico Build Action Latest
        uses: ./.github/workflows/analyze-image.yml
        with:
            image: samyarsadat/service_images
            image_tag: pico-build-action-latest
            analysis_name: pico-build-action-latest

    # No need to analyze latest. It is (currently) the same as Humble.
    # microros_build_action_latest:
    #     name: MicroROS Build Action Latest
    #     uses: ./.github/workflows/analyze-image.yml
    #     with:
    #         image: samyarsadat/service_images
    #         image_tag: microros-build-action-latest
    #         analysis_name: microros-build-action-latest

    microros_build_action_humble:
        name: MicroROS Build Action Humble
        uses: ./.github/workflows/analyze-image.yml
        with:
            image: samyarsadat/service_images
            image_tag: microros-build-action-humble
            analysis_name: microros-build-action-humble

    microros_build_action_jazzy:
        name: MicroROS Build Action Jazzy
        uses: ./.github/workflows/analyze-image.yml
        with:
            image: samyarsadat/service_images
            image_tag: microros-build-action-jazzy
            analysis_name: microros-build-action-jazzy