name: Analyze all BASE images
on: 
    push:
    schedule:
        - cron: '50 16 * * MON'   # Every Monday at 4:50 PM UTC

jobs:
    default_ubuntu_jammy:
        name: Default Ubuntu 22.04
        uses: ./.github/workflows/analyze-image.yml
        with:
            image: samyarsadat/custom_base_images
            image_tag: default-ubuntu-22.04

    default_alpine_latest:
        name: Default Alpine Latest
        uses: ./.github/workflows/analyze-image.yml
        with:
            image: samyarsadat/custom_base_images
            image_tag: default-alpine-latest

    base_ros_humble:
        name: Base ROS Humble
        uses: ./.github/workflows/analyze-image.yml
        with:
            image: samyarsadat/custom_base_images
            image_tag: base-ros-humble

    full_ros_humble:
        name: Full Desktop ROS Humble
        uses: ./.github/workflows/analyze-image.yml
        with:
            image: samyarsadat/custom_base_images
            image_tag: full-ros-humble