name: Push all SERVICE images to Docker Hub
on: 
    push:
    schedule:
        - cron: '30 16 * * MON'   # Every Monday at 4:30 PM UTC

permissions:
    packages: write
    contents: read

jobs:
    serverpi_caddy_latest:
        name: ServerPi Caddy Latest
        uses: ./.github/workflows/build-image.yml
        with:
            image: samyarsadat/service_images
            image_tag: serverpi-caddy-latest
            dockerfile_path: ./service_images/serverpi_caddy/Dockerfile_latest

    pico_build_action_latest:
        name: Pico Build Action Latest
        uses: ./.github/workflows/build-image.yml
        with:
            image: samyarsadat/service_images
            image_tag: pico-build-action-latest
            dockerfile_path: ./service_images/pico_build_action/Dockerfile_latest

    microros_build_action_latest:
        name: MicroROS Build Action Latest
        uses: ./.github/workflows/build-image.yml
        with:
            image: samyarsadat/service_images
            image_tag: microros-build-action-latest
            dockerfile_path: ./service_images/microros_build_action/Dockerfile_latest