name: Push all SERVICE images to Docker Hub
on: 
    push:
    schedule:
        - cron: '25 16 * * MON'   # Every Monday at 4:25 PM UTC

permissions:
    packages: write
    contents: read

jobs:
    serverpi_caddy_latest:
        name: ServerPi Caddy Latest
        uses: ./.github/workflows/build-image.yml
        with:
            image: samyarsadat/service_images
            image_tag: serverpi-caddy-latest
            dockerfile_path: ./service_images/serverpi_caddy/Dockerfile_latest
        secrets:
            DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
            DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

    serverpi_wgeasy_latest:
        name: ServerPi WireGuard-Easy Latest
        uses: ./.github/workflows/build-image.yml
        with:
            image: samyarsadat/service_images
            image_tag: serverpi-wgeasy-latest
            dockerfile_path: ./service_images/serverpi_wgeasy/Dockerfile_latest
        secrets:
            DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
            DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

    pico_build_action_latest:
        name: Pico Build Action Latest
        uses: ./.github/workflows/build-image.yml
        with:
            image: samyarsadat/service_images
            image_tag: pico-build-action-latest
            dockerfile_path: ./service_images/pico_build_action/Dockerfile_latest
        secrets:
            DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
            DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

    microros_build_action_latest:
        name: MicroROS Build Action Latest
        uses: ./.github/workflows/build-image.yml
        with:
            image: samyarsadat/service_images
            image_tag: microros-build-action-latest
            dockerfile_path: ./service_images/microros_build_action/Dockerfile_latest
        secrets:
            DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
            DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

    microros_build_action_humble:
        name: MicroROS Build Action Humble
        uses: ./.github/workflows/build-image.yml
        with:
            image: samyarsadat/service_images
            image_tag: microros-build-action-humble
            dockerfile_path: ./service_images/microros_build_action/Dockerfile_humble
        secrets:
            DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
            DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

    microros_build_action_jazzy:
        name: MicroROS Build Action Jazzy
        uses: ./.github/workflows/build-image.yml
        with:
            image: samyarsadat/service_images
            image_tag: microros-build-action-jazzy
            dockerfile_path: ./service_images/microros_build_action/Dockerfile_jazzy
        secrets:
            DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
            DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        
    excalidraw_arm64_latest:
        name: Excalidraw ARM64 Latest
        uses: ./.github/workflows/build-image.yml
        with:
            image: samyarsadat/service_images
            image_tag: excalidraw-arm64-latest
            dockerfile_path: ./service_images/excalidraw_arm64/Dockerfile_latest
            architectures: "linux/arm64"
        secrets:
            DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
            DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}