name: Push all SERVICE images to Docker Hub
on: 
    push:
        branches:
            - main
    schedule:
        - cron: '30 16 * * MON'   # Every Monday at 4:30 PM UTC

jobs:
    push_serverpi_caddy_latest:
        name: Push ServerPi Caddy (Latest) Image to Docker Hub
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read

        steps:
            - name: Check out the repo
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{secrets.DOCKER_USERNAME}}
                  password: ${{secrets.DOCKER_PASSWORD}}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: samyarsadat/service_images
                  tags: type=raw,value=serverpi-caddy-latest

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./service_images/serverpi_caddy/Dockerfile_latest
                  platforms: linux/arm64,linux/amd64
                  push: true
                  tags: ${{steps.meta.outputs.tags}}
                  labels: ${{steps.meta.outputs.labels}}


    push_pico_build_action_latest:
        name: Push Pico Build Action (Latest) Image to Docker Hub
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read

        steps:
            - name: Check out the repo
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{secrets.DOCKER_USERNAME}}
                  password: ${{secrets.DOCKER_PASSWORD}}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: samyarsadat/service_images
                  tags: type=raw,value=pico-build-action-latest

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./service_images/pico_build_action/Dockerfile_latest
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: ${{steps.meta.outputs.tags}}
                  labels: ${{steps.meta.outputs.labels}}

    push_microros_build_action_latest:
        name: Push MicroROS Build Action (Latest) Image to Docker Hub
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read

        steps:
            - name: Check out the repo
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{secrets.DOCKER_USERNAME}}
                  password: ${{secrets.DOCKER_PASSWORD}}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: samyarsadat/service_images
                  tags: type=raw,value=microros-build-action-latest

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./service_images/microros_build_action/Dockerfile_latest
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: ${{steps.meta.outputs.tags}}
                  labels: ${{steps.meta.outputs.labels}}