name: Push all images to Docker Hub
on: push

jobs:
    push_default_ubuntu_jammy:
        name: Push Default Ubuntu 22.04 Image to Docker Hub
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read

        steps:
            - name: Check out the repo
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{secrets.DOCKER_USERNAME}}
                  password: ${{secrets.DOCKER_PASSWORD}}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: samyarsadat/custom_base_images
                  tags: type=raw,value=default-ubuntu-22.04

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./default_ubuntu_22.04/Dockerfile
                  platforms: linux/arm64,linux/amd64
                  push: true
                  tags: ${{steps.meta.outputs.tags}}
                  labels: ${{steps.meta.outputs.labels}}


    push_default_alpine_latest:
        name: Push Default Alpine (Latest) Image to Docker Hub
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read

        steps:
            - name: Check out the repo
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{secrets.DOCKER_USERNAME}}
                  password: ${{secrets.DOCKER_PASSWORD}}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: samyarsadat/custom_base_images
                  tags: type=raw,value=default-alpine-latest

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./default_alpine_latest/Dockerfile
                  platforms: linux/arm64,linux/amd64
                  push: true
                  tags: ${{steps.meta.outputs.tags}}
                  labels: ${{steps.meta.outputs.labels}}


    push_serverpi_caddy_latest:
        name: Push ServerPi Caddy (Latest) Image to Docker Hub
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read

        steps:
            - name: Check out the repo
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{secrets.DOCKER_USERNAME}}
                  password: ${{secrets.DOCKER_PASSWORD}}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: samyarsadat/custom_base_images
                  tags: type=raw,value=serverpi-caddy-latest

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./serverpi_caddy_latest/Dockerfile
                  platforms: linux/arm64,linux/amd64
                  push: true
                  tags: ${{steps.meta.outputs.tags}}
                  labels: ${{steps.meta.outputs.labels}}