name: Push all BASE images to Docker Hub
on: 
    push:
        branches:
            - main
    schedule:
        - cron: '30 16 * * MON'   # Every Monday at 4:30 PM UTC

jobs:
    push_default_ubuntu_jammy:
        name: Push Default Ubuntu 22.04 Image to Docker Hub
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read

        steps:
            - name: Check out the repo
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{secrets.DOCKER_USERNAME}}
                  password: ${{secrets.DOCKER_PASSWORD}}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: samyarsadat/custom_base_images
                  tags: type=raw,value=default-ubuntu-22.04

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./base_images/default_ubuntu/Dockerfile_22-04
                  platforms: linux/arm64,linux/amd64
                  push: true
                  tags: ${{steps.meta.outputs.tags}}
                  labels: ${{steps.meta.outputs.labels}}


    push_default_alpine_latest:
        name: Push Default Alpine (Latest) Image to Docker Hub
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read

        steps:
            - name: Check out the repo
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{secrets.DOCKER_USERNAME}}
                  password: ${{secrets.DOCKER_PASSWORD}}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: samyarsadat/custom_base_images
                  tags: type=raw,value=default-alpine-latest

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./base_images/default_alpine/Dockerfile_latest
                  platforms: linux/arm64,linux/amd64
                  push: true
                  tags: ${{steps.meta.outputs.tags}}
                  labels: ${{steps.meta.outputs.labels}}


    push_base_ros_humble:
        name: Push ROS Humble (Base) Image to Docker Hub
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read

        steps:
            - name: Check out the repo
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{secrets.DOCKER_USERNAME}}
                  password: ${{secrets.DOCKER_PASSWORD}}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: samyarsadat/custom_base_images
                  tags: type=raw,value=base-ros-humble

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./base_images/base_ros/Dockerfile_humble
                  platforms: linux/arm64,linux/amd64
                  push: true
                  tags: ${{steps.meta.outputs.tags}}
                  labels: ${{steps.meta.outputs.labels}}


    push_full_ros_humble:
        name: Push ROS Humble (Full Desktop w/ Gazebo) Image to Docker Hub
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read

        steps:
            - name: Check out the repo
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{secrets.DOCKER_USERNAME}}
                  password: ${{secrets.DOCKER_PASSWORD}}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: samyarsadat/custom_base_images
                  tags: type=raw,value=desktop-full-ros-humble

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./base_images/desktop_full_ros/Dockerfile_humble
                  platforms: linux/amd64   # OSRF Profile ROS images are only available for AMD64
                  push: true
                  tags: ${{steps.meta.outputs.tags}}
                  labels: ${{steps.meta.outputs.labels}}