name: Push all BASE images to Docker Hub
on: 
    push:
    schedule:
        - cron: '30 16 * * MON'   # Every Monday at 4:30 PM UTC

jobs:
    default_ubuntu_jammy:
        name: Default Ubuntu 22.04
        uses: ./.github/workflows/build-image.yml
        with:
            image: samyarsadat/custom_base_images
            image_tag: default-ubuntu-22.04
            dockerfile_path: ./base_images/default_ubuntu/Dockerfile_22-04

    default_alpine_latest:
        name: Default Alpine Latest
        uses: ./.github/workflows/build-image.yml
        with:
            image: samyarsadat/custom_base_images
            image_tag: default-alpine-latest
            dockerfile_path: ./base_images/default_alpine/Dockerfile_latest

    base_ros_humble:
        name: Base ROS Humble
        uses: ./.github/workflows/build-image.yml
        with:
            image: samyarsadat/custom_base_images
            image_tag: base-ros-humble
            dockerfile_path: ./base_images/base_ros/Dockerfile_humble

    full_ros_humble:
        name: Full Desktop ROS Humble
        uses: ./.github/workflows/build-image.yml
        with:
            image: samyarsadat/custom_base_images
            image_tag: full-ros-humble
            dockerfile_path: ./base_images/desktop_full_ros/Dockerfile_humble
            architectures: "linux/amd64"   # OSRF Profile ROS images are only available for AMD64